# docker compose -f compose_name.yml up -d

version: '3'
services:
  r_v1:
    image: downey21/repo_private:r_v1
    stdin_open: true
    tty: true
    volumes:
      - ~/Project:/root/Project
      - ~/settings.json:/root/.vscode/settings.json