# docker compose -f compose_name.yml up -d

# docker run -dit \
#   --name r_v1 \
#   --volume  ~/Project:/root/Project \
#   --volume ~/settings.json:/root/.vscode/settings.json \
#   downey21/repo_private:r_v1

# docker exec -it r_v1 /bin/bash

version: '3'
services:
  r_v1:
    image: downey21/repo_private:r_v1
    stdin_open: true
    tty: true
    volumes:
      - ~/Project:/root/Project
      - ~/settings.json:/root/.vscode/settings.json
